### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by SwallowLong** [wohaiwo/web-going#14]
### 我想用下面的得到检索元素img所用的时间，但是为何会有不同的时间返回？是代码问题，还是什么？
```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<img src="myimage.gif" name="myImage">
	<script type="text/javascript">
	
	function a(){
		var start=Date.now();
		fn();
		var stop=Date.now();
		result=stop-start;
		alert(result);
    }
    function fn(){
		var images=document.getElementsByTagName("img");
	}
	a();
	</script>
</body>
</html>
```

**Comment by wohaiwo** [comment]
1. 首先我无法接受你给我代码的格式 不要以为只是一个demo 平时不养成习惯 在实际开发就不会去注意
   - 代码缩进不规范
   - `=` 两边需要空格 比如 ` var start = Date.now();`
2. DOM获取页面元素的时间其实可以忽悠不计 时间的不同也跟你在浏览器内存使用的因素有关系 可以尝试试试`for(let i = 0; i < 10000; i++) { // dosomething }` 来试试效果
3.  如果我看到不是很优先级的问题 我会留点时间让你自己思考 不会很快回答你  我希望你能自己多试几遍 就应该找到问题的所在了
4.  如果想通了 可以自己添加想通的过程  帮助你我的学习
